// Generated by https://quicktype.io

export interface PlacesResponse {
	type:        string;
	query:       string[];
	features:    Feature[];
	attribution: string;
}

export interface Feature {
	id:                   string;
	type:                 string;
	place_type:           string[];
	relevance:            number;
	properties:           Properties;
	text_es:              string;
	language_es?:         Language;
	place_name_es:        string;
	text:                 string;
	language?:            Language;
	place_name:           string;
	matching_text?:       string;
	matching_place_name?: string;
	bbox?:                number[];
	center:               number[];
	geometry:             Geometry;
	context:              Context[];
}

export interface Context {
	id:           string;
	wikidata?:    Wikidata;
	short_code?:  string;
	text_es:      string;
	language_es?: Language;
	text:         string;
	language?:    Language;
}

export enum Language {
	Es = "es",
	Nl = "nl",
}

export enum Wikidata {
	Q1489 = "Q1489",
	Q20236988 = "Q20236988",
	Q96 = "Q96",
}

export interface Geometry {
	type:        string;
	coordinates: number[];
}

export interface Properties {
	short_code?: string;
	wikidata?:   Wikidata;
	accuracy?:   string;
}
